env:
  browser: true
  jest: true
extends:
- eslint:recommended
- plugin:react/recommended
globals:
  React: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module
rules:
  # Add more rules later
  for-direction:
  - "error"
  getter-return:
  - "error"
  no-async-promise-executor:
  - "error"
settings:
  react:
    version: detect
