env:
  browser: true
  es6: true
  jest: true
extends:
- eslint:recommended
globals:
  React: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module
rules:
  # Only list rules that are not in *:recommended set
  # If rules are set to disable the one in *:recommended, please elaborate the reason
  no-async-promise-executor: error
  no-await-in-loop: error
  no-console:
  - error
  - allow:
    - error
    - warn
  no-extra-parens: error
  no-misleading-character-class: error
  no-template-curly-in-string: error
  require-atomic-updates: error
  accessor-pairs: error
  block-scoped-var: error
  class-methods-use-this: error
  # Re-enable later
  # complexity:
  # - error
  # - 5
  curly: error
  default-case: error
  dot-notation: error
  eqeqeq: error
  max-classes-per-file:
  - error
  - 2
  no-alert: error
  no-caller: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  # Re-enable later
  # no-magic-numbers: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions:
  - error
  - allowShortCircuit: true
    allowTernary: true
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  require-unicode-regexp: error
  wrap-iife: error
  yoda: error
  no-label-var: error
  # Re-enable later
  # no-shadow:
  # - error
  # - builtinGlobals: true
  #   hoist: all
  no-shadow-restricted-names: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars:
  - error
  - argsIgnorePattern: ^_$
    varsIgnorePattern: ^_
  no-use-before-define: error
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-sync: error
  arrow-body-style:
  - error
  - as-needed
  arrow-parens:
  - error
  - as-needed
  arrow-spacing:
  - error
  - after: true
    before: true
  generator-star-spacing:
  - error
  - after
  # no-confusing-arrow: // Will produce shorter code if allowed
  # - error
  # - allowParens: true // This will conflict with no-extra-parens
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing:
  - error
  - never
  # sort-imports: // Cannot group global or local imports and sort in differently
  # - error
  # - ignoreCase: true
  template-curly-spacing:
  - error
  - always
  yield-star-spacing:
  - error
  - after
  react/button-has-type: error
  react/default-props-match-prop-types: error
  react/destructuring-assignment: error
  react/forbid-component-props:
  - error
  - forbid:
    - style
  react/forbid-dom-props:
  - error
  - forbid:
    - id
  # react/forbid-prop-types: error // How to deal with Adaptive Card schema?
  react/no-access-state-in-setstate: error
  react/no-array-index-key: error
  react/no-danger: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-redundant-should-component-update: error
  react/no-typos: error
  react/no-this-in-sfc: error
  react/no-unescaped-entities: error
  react/no-unsafe: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prefer-read-only-props: error
  react/require-default-props: error
  react/self-closing-comp: error
  react/sort-prop-types: error
  react/state-in-constructor: error
  react/static-property-placement:
  - error
  - property assignment
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
  react/jsx-boolean-value:
  - error
  - always
  react/jsx-closing-bracket-location:
  - error
  - tag-aligned
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing:
  - error
  - when: always
  react/jsx-equals-spacing:
  - error
  - never
  react/jsx-first-prop-new-line:
  - error
  - multiline-multiprop
  react/jsx-handler-names: error
  react/jsx-indent:
  - error
  - 2
  react/jsx-indent-props:
  - error
  - 2
  react/jsx-max-props-per-line:
  - error
  - maximum: 1
    when: multiline
  react/jsx-no-bind: error
  react/jsx-no-literals: error
  react/jsx-one-expression-per-line:
  - error
  - allow: literal
  react/jsx-fragments:
  - error
  - syntax
  react/jsx-pascal-case: error
  react/jsx-props-no-multi-spaces: error
  react/jsx-sort-default-props: error
  react/jsx-sort-props: error
  react/jsx-tag-spacing:
  - error
  - afterOpening: never
    beforeClosing: never
    beforeSelfClosing: always
    closingSlash: never
  # react/jsx-wrap-multilines: error // Conflict with no-extra-parens
settings:
  react:
    version: detect
