language: node_js
node_js:
  - "9"
env:
  # This is SAS based on https://xxx.blob.core.windows.net/botframework-webchat/
  - secure: "cWqnxN9B5XfPgozA+4hgVtB2SkvMI5VkNvKID8/59Ut1zZB5Zli4+FcDMyN7ebUwQ+dqDlQx4RSBcZS//M6/3opd4nIDrEHCwct+6/iJbYc1SLv/tfwVDkXXxpv5+W3rLqGqE8GiLjwErksNp5Sda/gXfPqOYqZWkBVF0gPGw5IVdYyzw9gVSiF6/Y/ojJot0E+cnZx7LbWtEYLP7mSokYoXf1nVNqiBYxCjUvYgIHBgnskMMnO6UjqszNqWvMLajfkAe778iBPzRu3s0LF693CdP6yWPS0tzx9b9gJPsErTiYQizz34IA1hJkZFeSdwcyjBzsGuBTRq+0H59Q44MLi92cMYt7OI5Re+oneCzELPYcZmDA4MdpnDS6bGvj4DLXSKRYwU1TUAebnbj6NtuTlqb1z1H4TFTR5Mf84sNNvcdanzD/16vJlQfe7x49fAL6QVirc+1dO7LIcMK3WLigigYbS5rmwg+0lM+LpMnDB+LESS2YfqwxzAONXL3GRgfkmNJ4CqM149h70ldZhL8nvM1ybHzHclnBawwww8wF4nLmqbNzyeSK2kVS01mtMMeL6IRgCwjmoMVWztTUyT0qnLiJgJQ7diqo6ryHjezY17bo+t6D/wmWywjp0a1SGRe0BeZKzKhcIfVRhXqQfwYjy+ZhY9SpOI1hLBxz7mBw0="
install:
  - npm install
  - npm run install-test
before_script:
  - npm run build
  - npm run build-test
script:
  # Our tests currently don't run on Travis, disabling them for now
  - npm --version
before_deploy:
  - git config --local user.name "Bot Framework"
  - git config --local user.email "botframework@microsoft.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "ow4+DeFWxK5eSiId/c8jkRi6vPc97GgrtgP71SQFxVrcA3tKnDLtaZ4pxDeU+HdMpfdiGq75MQLJMT0UDw7WV3il/HWyTYyJzV6yG12Kw/fv0Rc08in0ImGT7BTt5DVSKqCOD9rpD3MZx3oLqLIVz8wqpVu33w+i6dsPyTQeiJPJ/p/hn6mxt0EcEXaULcYk+gFEiSz0tbP/Ak4CCIC40876T3e3CE8HlE+8Ru8fToeK98ZHLcnVpRcNwgb6qApY09gluJ+ylVVRXK49ofnPyD2KsabPdPv7py1GmmYEXhFLtuIrnTm+yPKKTaVOejbhYO32Z/uRZvr6zjyickVWua4uGm2JqCrg+NHjdiBdKdKM97kq2JvcESt/B4QJLgY2jpd/urgwL272rNpK6psDjpvUBLadnCP8HFqizSWBg23r01wZj2W2cNdiLqvJRfFUQZ4RnshifdBROiiKt88BBkIx3MxaI/OS8I8cODwSPcbA87ptZfzHHtcL39aNAQ9uuvv5kqA6I1tpujm/NJJiIA3xqnoHs0cUjXQEJ8GIIJnap798xsh/0sqfra54PNg8ICw1wXaBlY8qJjkGnqROtdW8dQY4IxOvSKZX8gjpVKw20C2qlJofvUHTkfvQhJz/S1iD5b20IlxEbclRf3fciqU+cx7LkwyUJs7FFZkzUdU="
    email: "botframework@microsoft.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
