sudo: required

language: node_js

node_js:
- "12"

services:
- docker

before_install:
- npm ci

install:
- npm run bootstrap
- npm run esilnt
- npm run build

script:
- docker-compose up --build --detach
- npm test -- --ci --coverage true --maxWorkers=4 --no-watch
- docker-compose down --rmi all

deploy:

# Upload image snapshots to build artifact curator
- provider: script
  script:
  - zip -r image-snapshots __tests__/__image_snapshots__/
  skip_cleanup: true
  on:
    branch: master
