language: node_js
node_js:
  - "9"
env:
  # CDN_BLOB_ACCOUNT
  - secure: "xcIL1eZ+WVF8fjfNZHmy0ouVjkCCDI1DdqIjqKRrIFlsoo1ihTXlF8SAM91t6u9PHwef7r9qQB0shfe/9+Lv1pd+0JAloU24l+l9i3MYx7sHbh7Dv9qxT8NDTvXXflklvrUrrjCBvyIuEeL8IorPoL48S5+LfUEl4ezcoWNYCV//8I1lPZpwjWema3WANByBGCrOZl0Maa8OThvBYhq9A29Oq8tbt5SeBqpIiX6ougi9LKvAEs7i7XarC+28AqYM3OWTo+PHy9rlJyHK3KiTtRMlWhOdEileu7gyiwtY38rW8UDFQfRo/37Ugkeld5EdvaQwCBxaSq+p1oiUSVk0TdFiop/hEgi4Q/jfnAQN5xQ+kWT3ObzH/KUTWO+4KDE7PAW+TggMHm/kgDYe8sb7nvft2CalRmYXgU6aIHAr9A/H4nJOluxrXQ0zBKGVc0EodADfBD6LYPGPSrwtZDB48fn4PboyqFV9V9tvtFMsTqiT73lCbo7oyg7L7zTXzLi10nCAJSD4CuMvq/ERfXoBRKOAAFzRnX29XEfo/TRF0k+zqCyuGxS7QM0aZjxbipFpQ2SgJxT9HrfFTZiymnjzmAvde+F83TPT+CHjDE4WgDGL+zkwoVwTscChODPosZySTaJJhu7bqUQo66jzK2a5NR2wOaPpiktrAelilKsGKSA="
  # CDN_BLOB_KEY, this is a SAS based on https://xxx.blob.core.windows.net/botframework-webchat/, expiring on 2019-06-06
  - secure: "exL8fK/pie5VsWnxM76ukP4B/GmuUXJVx/PewpzTh/jZvDzciJnQuynisswNLXkZl1uT6Am9Ju1s0JYOmo8EJuWTuFfcPgTedaUdQ0F+nsIvGBq4blpNeSTBljNDcX92xRsdq4LHaupvchu7D5/umlSEnONDVZHspzRPiDJZ1WxCaV3LzUBHnWqGZ2YQ3h1X7rw5z24lJza8oZH0kHLEhv/kIZRSrK5vFBfyn9LizhqmTYwSEyelHg6hZgVP2nsOCbV9rucc9nbdOrsQVUKs8vNbMd5oybtnoPlNLHfeOfNgDV6oujwpQPx7TnUIwfNCkn5KzetHdfvButdNwiOzKsOToRG2DmAcsGnJ+AoBAzgiMUoXYD/MHOW2GBcoLSCCmztusBh8zRnmzVbwMIe+/DxE/ZueaWWj1cXacIl+bFBzmT3SVNbn7Oxo4osEQ9jyZbspXaqnlUZUYsFbyIl2egEOUAV0bJYrR9k73K7fgWk4wpCy6dnytQn9NJgcrYmMXuzXjS4zbdibjlVYWo4mQrSLIqu09RKNDXliij3nUyJpYh8sKzZC+uCbDaiVv+oNe4jbkX+SmpoA1I6NXWC0fsYYd84rNh5dSPYBAtvY54PGit99MF/KacMNOO7/130+1h54OSkvKcgk2Vy1tvKQi5GHYZBRSxmmb2swqfP3dfU="
install:
  - npm install
  - npm run install-test
before_script:
  - npm run build
  - npm run build-test
script:
  # Our tests currently don't run on Travis, disabling them for now
  - npm --version
before_deploy:
  - git config --local user.name "Bot Framework"
  - git config --local user.email "botframework@microsoft.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "ow4+DeFWxK5eSiId/c8jkRi6vPc97GgrtgP71SQFxVrcA3tKnDLtaZ4pxDeU+HdMpfdiGq75MQLJMT0UDw7WV3il/HWyTYyJzV6yG12Kw/fv0Rc08in0ImGT7BTt5DVSKqCOD9rpD3MZx3oLqLIVz8wqpVu33w+i6dsPyTQeiJPJ/p/hn6mxt0EcEXaULcYk+gFEiSz0tbP/Ak4CCIC40876T3e3CE8HlE+8Ru8fToeK98ZHLcnVpRcNwgb6qApY09gluJ+ylVVRXK49ofnPyD2KsabPdPv7py1GmmYEXhFLtuIrnTm+yPKKTaVOejbhYO32Z/uRZvr6zjyickVWua4uGm2JqCrg+NHjdiBdKdKM97kq2JvcESt/B4QJLgY2jpd/urgwL272rNpK6psDjpvUBLadnCP8HFqizSWBg23r01wZj2W2cNdiLqvJRfFUQZ4RnshifdBROiiKt88BBkIx3MxaI/OS8I8cODwSPcbA87ptZfzHHtcL39aNAQ9uuvv5kqA6I1tpujm/NJJiIA3xqnoHs0cUjXQEJ8GIIJnap798xsh/0sqfra54PNg8ICw1wXaBlY8qJjkGnqROtdW8dQY4IxOvSKZX8gjpVKw20C2qlJofvUHTkfvQhJz/S1iD5b20IlxEbclRf3fciqU+cx7LkwyUJs7FFZkzUdU="
    email: "botframework@microsoft.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
