version: '3'

services:
  # On Windows, run with COMPOSE_CONVERT_WINDOWS_PATHS=1

  chrome:
    build:
      context: ./
      dockerfile: Dockerfile-selenium
    depends_on:
    - selenium-hub
    - webchat-html
    - webchat-webdriver
    environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444

  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    container_name: selenium-hub
    environment:
    - GRID_BROWSER_TIMEOUT=60
    - GRID_TIMEOUT=60
    ports:
    - "4444:4444"

  webchat-html:
    build:
      context: ./
      dockerfile: Dockerfile-testharness-html
    ports:
    - "5081:80"

  webchat-webdriver:
    build:
      context: ./
      dockerfile: Dockerfile-testharness-webdriver
    ports:
    - "5080:80"
