version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file: ./bot/.env
    image: webchat.azurecr.io/webchat-sample-upload-to-blob-bot
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file: ./rest-api/.env
    image: webchat.azurecr.io/webchat-sample-upload-to-blob-bot
    ports:
      - "3000:5000"
