name: Daily build

on:
  push:
    paths:
      - .github/workflows/daily-release.yaml
  schedule:
    - cron: 00 03 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - run: npm ci --no-production

      - name: Propagate versions
        run: node_modules/.bin/lerna version --exact --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`

      - run: npm run bootstrap
      - run: npm run build
        env:
          NODE_ENV: production

      - name: Run npm pack api
        run: |
          cd packages/api
          npm pack

      - name: Run npm pack bundle
        run: |
          cd packages/bundle
          npm pack

      - name: Run npm pack component
        run: |
          cd packages/component
          npm pack

      - name: Run npm pack core
        run: |
          cd packages/core
          npm pack

      - name: Run npm pack directlinespeech
        run: |
          cd packages/directlinespeech
          npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: |
            packages/api/*.tgz
            packages/bundle/*.tgz
            packages/component/*.tgz
            packages/core/*.tgz
            packages/directlinespeech/*.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: packages/bundle/dist/**/*

      - id: compute-hash
        name: Compute build metadata
        run: |
          echo "::set-output name=build-date::`date \"+%Y-%m-%d %R:%S\"`"
          echo "::set-output name=package-version::`tar -xOzf packages/bundle/webchat-*.tgz package/package.json | jq -r '.version'`"
          echo "::set-output name=release-tag-name::daily"
          echo "::set-output name=sha384-es5::`cat packages/bundle/dist/webchat-es5.js | openssl dgst -sha384 -binary | openssl base64 -A`"
          echo "::set-output name=sha384-full::`cat packages/bundle/dist/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`"
          echo "::set-output name=sha384-minimal::`cat packages/bundle/dist/webchat-minimal.js | openssl dgst -sha384 -binary | openssl base64 -A`"

      - name: Display build metadata
        run: |
          echo build-date=${{ steps.compute-hash.outputs.build-date }}
          echo release-tag-name=${{ steps.compute-hash.outputs.release-tag-name }}
          echo package-version=${{ steps.compute-hash.outputs.package-version }}
          echo sha384-es5=${{ steps.compute-hash.outputs.sha384-es5 }}
          echo sha384-full=${{ steps.compute-hash.outputs.sha384-full }}
          echo sha384-minimal=${{ steps.compute-hash.outputs.sha384-minimal }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.compute-hash.outputs.release-tag-name }}
          release_name: Daily build $GITHUB_REF
          body: |
            This build will be updated daily. **Please do not use this build in production environment.**

            | Build time | Run ID | Source version | Git ref | Package version |
            | - | - | - | - | - |
            | ${{ steps.compute-hash.outputs.build-date }} | [`$GITHUB_RUN_ID`](${{ $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID }}) | [$GITHUB_SHA]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA) | `$GITHUB_REF` | `${{ steps.compute-hash.outputs.package-version }}` |

            ```html
            <script
              crossorigin="anonymous"
              integrity="sha384-${{ steps.compute-hash.outputs.sha384-full }}"
              src="https://github.com/microsoft/BotFramework-WebChat/releases/download/${{ steps.compute-hash.outputs.release-tag-name }}/webchat.js"
            ></script>

            <script
              crossorigin="anonymous"
              integrity="sha384-${{ steps.compute-hash.outputs.sha384-es5 }}"
              src="https://github.com/microsoft/BotFramework-WebChat/releases/download/${{ steps.compute-hash.outputs.release-tag-name }}/webchat-es5.js"
            ></script>

            <script
              crossorigin="anonymous"
              integrity="sha384-${{ steps.compute-hash.outputs.sha384-minimal }}"
              src="https://github.com/microsoft/BotFramework-WebChat/releases/download/${{ steps.compute-hash.outputs.release-tag-name }}/webchat-minimal.js"
            ></script>
            ```

            > Note: the SHA384 hash may change daily.
          draft: false
          prerelease: true
