name: Daily build

on:
  push:
    paths:
      - .github/workflows/daily-release.yaml
  schedule:
    - cron: 00 03 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - run: npm ci --no-production

      - name: Propagate versions
        run: node_modules/.bin/lerna version --exact --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`

      - run: npm run bootstrap
      - run: npm run build

      - name: Run npm pack api
        run: |
          cd packages/api
          npm pack

      - name: Run npm pack bundle
        run: |
          cd packages/bundle
          npm pack

      - name: Run npm pack component
        run: |
          cd packages/component
          npm pack

      - name: Run npm pack core
        run: |
          cd packages/core
          npm pack

      - name: Run npm pack directlinespeech
        run: |
          cd packages/directlinespeech
          npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: |
            packages/api/*.tgz
            packages/bundle/*.tgz
            packages/component/*.tgz
            packages/core/*.tgz
            packages/directlinespeech/*.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: packages/bundle/dist/**/*

      # - id: deploy
      #   uses: azure/webapps-deploy@v2.1.2
      #   with:
      #     app-name: webchat-playground
      #     slot-name: production
      #     publish-profile: ${{ secrets.PLAYGROUND_PUBLISH_PROFILE }}
      #     package: packages/playground/build.zip

      # - name: Ping deployment
      #   run: |
      #     sleep 15
      #     curl -s ${{ steps.deploy.outputs.webapp-url }}
