name: samples/07.a.upload-to-azure-storage

on:
  push:
    branches:
      - master
      - sample*

env:
  APP_NAME: webchat-samples-uploadazurestorage
  DOCKER_REGISTRY: webchatsamples.azurecr.io
  DOCKER_REPOSITORY: webchat-samples-uploadazurestorage
  DOCKERFILE_PATH: samples/07.advanced-web-chat-apps/a.upload-to-azure-storage
  PUBLISH_PROFILE: ${{ secrets.SAMPLES_UPLOADAZURESTORAGE_PUBLISH_PROFILE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Read variables
        id: variables
        run: |
          echo "::set-output name=short_sha::${GITHUB_SHA:0:7}"

      - name: Build and push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
        uses: docker/build-push-action@v1
        with:
          password: ${{ secrets.SAMPLES_DOCKER_PASSWORD }}
          path: ${{ env.DOCKERFILE_PATH }}
          registry: ${{ env.DOCKER_REGISTRY }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tag_with_sha: true
          tags: latest
          username: ${{ secrets.SAMPLES_DOCKER_USERNAME }}

      - name: Publish to ${{ env.APP_NAME }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:sha-${{ steps.variables.outputs.short_sha }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
